/*

A Rigid Body

*/

#include "rigid_body.h"
#include "Utils/log_manager.h"

// C4316: object allocated on the heap may not be aligned 16. 
// this waring is generated by the Bullet version 2.82. Nothing can be done, so disable it. 
#pragma warning(disable: 4316)

using namespace std;

namespace NYX {

RigidBody::RigidBody(std::string name, uint id) :
	PhysicsBody(name, id),
	mBulletRigidBody(NULL)
{
	mBodyType = BDY_RIGID;
}

RigidBody::~RigidBody()
{
    mBulletRigidBody = NULL;
}

void RigidBody::Finilize()
{
	mBulletMotionState = new btDefaultMotionState(mBulletTransform);
	btRigidBody::btRigidBodyConstructionInfo rbInfo(mMass,mBulletMotionState,mBulletCollisionShape,mBulletInertia);
	mBulletRigidBody = new btRigidBody(rbInfo);

	mBulletRigidBody->setLinearVelocity(btVector3(mVelocity.X(), 
												  mVelocity.Y(),	
												  mVelocity.Z()) );

	mBulletRigidBody->setFriction(mFriction);

	mBulletRigidBody->setDamping(mDamping, mAngularDamping);

	mIsInitialized = true;
}

void RigidBody::CalculateTotalForce()
{
	//mBulletRigidBody->applyForce(btVector3(0.21, 0.0, 0.0), btVector3(0.1, 0.0, 0.2));
}

}


